### ISSUE TITLE
Repos are Created, but Artifacts do not Migrate

### ISSUE THREAD

**Issue by stutefish** [JFrogDev/nexus2artifactory#17]
I have configured the tool and it connects to Artifactory. It migrates the Users and the Repos, but when it tries to migrate the Artifacts, they all fail.

In my logs, I see a lot of calls to repo names that don't exist.

For example, one of the repos I'm migrating is named *snapshots*. In my logs, I see a lot of PUT calls to URIs like 
- snapshots*z*
- snapshots*m*
- snapshots*l*
etc. 

These bogus URI calls all return HTTP 403. I never see any calls to PUT or POST actual artifacts in the actual "snapshots" repo. 

Again, the repos have been created by the tool. Connectivity works. Permissions work.

` + Repositories   2/2`
` + Groups         0/0`
` + Users          2/2`
` + Permissions    0/0`
 `+ LDAP Configs   0/0`
 `! Artifacts      3407 Total, 3407 Errors`
 `+ Finalizing     2/2`

**Comment by DarthFennec** [comment]
That is very strange. Could you provide your Nexus version, and debug logs from the migration tool? You can get logs by passing `-v debug -l logfile.log` when you run the tool. Thanks!

**Comment by stutefish** [comment]
I'm waiting to hear back from my Nexus admin about the version. 

Uploaded my log file. I replaced the actual hostname of the Artifactory node with a dummy string. Other than that, the file is as written by the tool. 
[n2a-log.txt.zip](https://github.com/JFrogDev/nexus2artifactory/files/1728969/n2a-log.txt.zip)

**Comment by stutefish** [comment]
Nexus version is 2.12

**Comment by DarthFennec** [comment]
So it looks like each file path is being replaced by a single letter `l`, `m`, `r`, `s`, or `z`. I'm uncertain what (if any) significance those letters in particular have.

In Nexus, each artifact on the filesystem has an accompanying metadata file. The migrator reads this file to decide what path to deploy the artifact to. It's possible that your Nexus instance's metadata files contain incorrect information; they list single letters instead of full paths. If you could verify whether that is actually the case, that would be fantastic.

If you can find an artifact at `sonatype‑work\nexus\storage\releases\foo\bar\baz.jar`, the metadata for that artifact is located at `sonatype‑work\nexus\storage\releases\.nexus\attributes\foo\bar\baz.jar`. This is always a JSON file, regardless of its file extension. It should have a field called `"storageItem-path"`, and this is the value the migrator uses as the deploy path. It should start with a slash, and should match the path of the artifact relative to the repository folder.

**Comment by peters95** [comment]
closing this issue due to age.
