### ISSUE TITLE
Issue migrating N3 to Artifactory

### ISSUE THREAD

**Issue by mamaamacriminal** [JFrogDev/nexus2artifactory#25]
Hello!
Currently I`m facing am issue when try to migrate Nexus3 to Artifactory.
2018-05-30 09:52:02,983 [MainThread] [INFO] (nex2art.core.Nexus3:167) - Successfully fetched Nexus data.
2018-05-30 09:52:02,983 [MainThread] [INFO] (nex2art.core.Nexus3:58) - Successfully read repository config.
2018-05-30 09:52:02,983 [MainThread] [INFO] (nex2art.core.Ldap3:12) - Reading LDAP config from Nexus.
2018-05-30 09:52:02,983 [MainThread] [INFO] (nex2art.core.Ldap3:16) - Successfully read LDAP config.
2018-05-30 09:52:02,983 [MainThread] [INFO] (nex2art.core.Security3:60) - Reading security config from Nexus.
2018-05-30 09:52:02,986 [MainThread] [ERROR] (nex2art.core.Security3:95) - Error reading security config:
Traceback (most recent call last):
  File "/home/ykochubey/nexus2artifactory-master/nex2art/core/Security3.py", line 73, in refresh
    roledata = self.getrole(role, privmap)
  File "/home/ykochubey/nexus2artifactory-master/nex2art/core/Security3.py", line 135, in getrole
    for priv in role['privileges']: privs.append(privmap[priv])

Here is the short trace.

**Comment by DarthFennec** [comment]
I think you might have a role that contains a privilege which doesn't exist. I'm a little surprised at this, since I feel like Nexus would prevent this kind of thing on the database level. So there might be something else going on.

Now that I think about it, this exact issue was submitted by [someone else](https://github.com/JFrogDev/nexus2artifactory/issues/19#issuecomment-381245329) a while back. I gave him some steps to follow in order to help debug:

>You're right, Nexus 3 stores all of this data in the database. I use a [simple groovy script](https://github.com/JFrogDev/nexus2artifactory/blob/master/nex2art/resources/plugin.groovy) to extract all the data for the migrator to use, and I'm pretty certain it shouldn't be missing or forgetting anything, so the output from that should reflect what you would find in the database. I expect if you [ran the script](https://help.sonatype.com/repomanager3/rest-and-integration-api/script-api), you'd find a group with a permission `nx-repository-view-maven2-central-browse`, but no permission entry of that name (and probably no `maven2-central` repository).

He never got back to me, but if you can take a look at the output of that script, we can at least figure out if the migrator is doing something wrong here, or if there's a bad reference in the Nexus database itself. From there, we can get a better idea of how to fix the problem. Thanks!

**Comment by mamaamacriminal** [comment]
Just found a lame thing, that our Nexus ver doesn`t have Script API and a bit outdated(for 1.5 yrs lol). Will share you my results after updating.

**Comment by DarthFennec** [comment]
I'm fairly certain the script API is available on all Nexus 3 versions. It certainly works on yours, since that's how the migrator extracts data in the first place, and your migration got at least that far before encountering your error. I believe it's not working for you because they recently changed the API path. `/service/rest/v1/` is the newer path, but on older versions you should be able to reach the same services through `/service/siesta/rest/v1/`.

**Comment by mamaamacriminal** [comment]
Version Nexus 3.2.1-01 doesn`t have this API =) Found an issue its the same you`ve told to those guys.
If you`re had a repo BLAH-BLAH with some privs on it and roles contains that privs and deleted this repo, it will make privs "disappear" but not delete them from another elements.

**Comment by DarthFennec** [comment]
Yeah, you're right. If it's a user-created privilege, it works fine, but if it's one of the privileges that Nexus creates automatically when the repository is created, this happens.

I pushed a fix. Let me know if it works for you.

**Comment by peters95** [comment]
Closing this issue due to age
