### ISSUE TITLE
Filter by type 

### ISSUE THREAD

**Issue by daniloichaves** [JFrogDev/nexus2artifactory#29]
I'm using nexus2artifactory and a feacture that i was not apple to find is to filter all type hosted for to migrate.

**Comment by DarthFennec** [comment]
Yeah, the filter system is very basic at the moment (as it's one of the more recent features), and currently only supports filtering by name. More filtering options will be added eventually, though we don't have a timeframe for it right now.

Luckily, this turned out to be a simple change, so I took the liberty of pushing an update. You can now filter repositories by package type (`type=maven`) and by class (`class=local`, `class=remote`, `class=virtual`). Let me know if you have any issues with this. Thanks!

**Comment by peters95** [comment]
Closing this issue due to age
