### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by screig** [JFrogDev/nexus2artifactory#41]
Hi

I have a nexus3 repo. I start the app and go to the inital setup, I then put in the nexus data directory. The inputted-text goes green then asks me for three other fields:

- Url

- Nexus Username

- Nexus Password

I enter these three fields and each of them turn green. However at this point the data-directory field turns red. If I then remove the url, the data-directory returns to green. It seems I can only have one or the other (be green)?

Any ideas? 
Thanks
Sean

![image](https://user-images.githubusercontent.com/4292074/60897033-3d90bf80-a25f-11e9-9794-14dfdf77c602.png)

![image](https://user-images.githubusercontent.com/4292074/60897074-526d5300-a25f-11e9-9dbf-c072494778e9.png)

**Comment by DarthFennec** [comment]
You're right, the UI behavior here could be more intuitive. Here's what's going on:

- The data directory field turns green if the tool can verify that the directory exists and contains Nexus data (and turns red if it can't).
- The data directory field also turns green if the tool can successfully read valid migration data from the Nexus server (and turns red if it can't).

Your directory field is green after the directory is verified, but before the URL is accessed. Once the data is downloaded from the URL, there's an error reading the data, so the field turns red. If you change the URL, the data read from the old URL is considered out of date, and the field reverts to green because the directory itself is still valid.

<hr>

So your problem is that the tool encounters an error when reading the data sent by Nexus. Do you get an error message when that happens? If you run the tool with the `-l` option, it should provide a log detailing the error.

**Comment by screig** [comment]
thanks, for the response, makes sense.

**Comment by danielbmeireles** [comment]
Hello @DarthFennec, how are you?

I'm facing the same issue / behaviour when I try to configure the initial setup.

I ran the tool with the log enable and I got the following error message:

`2019-08-21 14:50:09,677 [MainThread] [INFO] (nex2art.core.Security3:60) - Reading security config from Nexus.
2019-08-21 14:50:09,679 [MainThread] [ERROR] (nex2art.core.Security3:95) - Error reading security config:
Traceback (most recent call last):
  File "/home/meireld/nexus2artifactory/nex2art/core/Security3.py", line 73, in refresh
    roledata = self.getrole(role, privmap)
  File "/home/meireld/nexus2artifactory/nex2art/core/Security3.py", line 138, in getrole
    privs.append(privmap[priv])
KeyError: u'deployer'
2019-08-21 14:50:09,679 [MainThread] [INFO] (nex2art.core.Format:124) - Updating data tree with Nexus data.`

If you need any extra data, please just let me know.

Thanks!
Daniel

**Comment by DarthFennec** [comment]
@danielbmeireles Actually I think this is a typo on my end, I had an `or` instead of an `and`. Pushed a fix, see if that helps. Thanks!

**Comment by danielbmeireles** [comment]
@DarthFennec Worked like a charm! Thank you so much!

**Comment by vpbobade** [comment]
@DarthFennec  Can I use it if my nexus is container based. Which directory path should I enter for the Nexus. to make the migration work. Please guide.

**Comment by DarthFennec** [comment]
@vpbobade I'll answer you in the other issue you made with a similar question, #58. And I think I'll close this one, it seems resolved.
