### ISSUE TITLE
Users Migration Setup

### ISSUE THREAD

**Issue by kb7791** [JFrogDev/nexus2artifactory#43]
I'm trying to migrate from the latest Nexus 2 to the latest Artifactory pro using the 30 day trial as proof of concept for my company.

So when using the tool per instructions Security Migration setup is telling me that edits need to be made.
![image](https://user-images.githubusercontent.com/11503681/61822011-9b5c0480-ae26-11e9-8590-f02a32f1a034.png)

Then when I step into security Migration set up the following needs to be edited.
![image](https://user-images.githubusercontent.com/11503681/61822161-f4c43380-ae26-11e9-9865-c2752d1dd64a.png)

When looking at my user that need to have edits, they all seem to have email and password fields in need of editing. How am i supposed to get around this when i check Nexus2 and the users have emails associated with them but don't seem to get pulled into the migration tool, also looks like it wants me to edit their passwords too! Not sure if this is a Nexus2 config issue since ldap is being used or just a tooling issue. Please advise and thank you in advance.

**Comment by DarthFennec** [comment]
If your users have emails associated with them, the tool should be picking those up, I'm not sure why it wouldn't be. I think I would need to see the Nexus instance in more detail to figure out what's going on there. There may be something wrong with your instance, or a bug in the tool, and in either case I'll do what I can to help. My best guess is that it has something to do with the LDAP.

If your users do not have associated emails, all of the emails would need to be set within the tool, since Artifactory doesn't allow users to be created without emails under normal circumstances. If all the emails can be programmatically discovered via the usernames, you can save the configuration as a JSON file and write a script that fills in the missing fields appropriately, and then run the tool again and load the modified JSON file. The only alternatives to this at the moment are filling in each field by hand, or setting all fields to the same value via the "mass edit" option, but you probably don't want to do either of those.

As for the passwords, they can't be migrated at all, for security reasons. For users with admin permissions, passwords must be set manually in the tool, but for all other users, you can set the "Default Password" field. This will set all unset passwords to the same default value temporarily, and then Artifactory will ask each user to change their password when they first log in.

If your users are all on LDAP, I don't know how much of the above applies to you. As long as LDAP is configured in Artifactory, your users should be able to log in whether they're migrated or not (although, if they hadn't been migrated, their groups and permissions will be set to defaults and would need to be reassigned). This may be the simplest option.

**Comment by kb7791** [comment]
This is my profile for example in nexus
![image](https://user-images.githubusercontent.com/11503681/61880570-22f75100-aec3-11e9-9699-338b259b2cdb.png)
and in the tool my email isnt getting pulled in
![image](https://user-images.githubusercontent.com/11503681/61881277-5a1a3200-aec4-11e9-8d7e-a0bc0fe47e55.png)
 out of all the users maybe like 4 of them came over with emails attached, and as far as I can see in Nexus all users have emails associated with there profiles

**Comment by DarthFennec** [comment]
That's strange. Perhaps if we can look at how these users are being stored, it would shed light on why their emails are not being migrated.

If you can, go into your Nexus data directory in your filesystem (where you tell the tool to look for Nexus), and in the `conf` folder, find the `security.xml` file. This should contain, among other things, all of the data for all of the users in Nexus. Try to find one example of a user that kept its email, and one example that didn't, so we can compare them. There should just be an `email` field, and that's what the tool looks for, but if those users have their emails stored in some other way, I can add logic to the tool to look for that as well.

**Comment by kb7791** [comment]
So based on what I can see in the security.xml file in Nexus these seem to populate with the emails.

![image](https://user-images.githubusercontent.com/11503681/61908741-5e634100-aefe-11e9-9c93-71762d63605b.png)
 The other user just as u suspected are coming from this section of the xml and there isnt an email field.
![image](https://user-images.githubusercontent.com/11503681/61909526-64f2b800-af00-11e9-8a37-ab3b5a6d89fb.png)

So when I look at nexus UI on my earlier screen shot, I wonder where those email fields are being stored??

**Comment by kb7791** [comment]
Seems as if in Nexus some, well most of the user were created using the option of External User Role Mapping. Looks like it maybe querying LDAP. tested it out by entering my user ID and hiot search and it filled in all my fields on Nexus User info card

**Comment by DarthFennec** [comment]
That makes sense. So then it appears that "External User Role Mapping" users have no `<user>` entry, just a `<userRoleMapping>` entry with a `<source>` set to `LDAP`. Which means the only way to get these users' emails would be to query LDAP during import.

I just tested this, and it should work, but you should make sure it works in your case as well, if you like the idea. If you set the filter to only LDAP users (or users with empty email addresses), you can use the mass edit function to set all of their emails to some dummy email. You can also use the default password field to set a dummy password, it shouldn't matter. Now, when a user logs in, they'll use their LDAP password, (and not the dummy one), which will log them in through LDAP. This will cause their dummy email address to automatically be overwritten with the correct address from LDAP.

**Comment by kb7791** [comment]
I like this idea. My question is since I have a small mix of `<users>` and `<userRoleMapping>` will mass email and password edits overwrite the existing `<users>` that I want to keep?

**Comment by kb7791** [comment]
ahhh...forget it, should have read your response more thoroughly. Ill use the filter to mass edit

**Comment by kb7791** [comment]
Going to have a real noob question, any idea what the syntax in the filter would be to pull only the ldap users?

**Comment by DarthFennec** [comment]
Not a noob question, that's my bad actually. I forgot that the filter functionality isn't fully implemented yet; right now you can only filter by username. I'll see if I can add what you need today, and I'll let you know.

**Comment by kb7791** [comment]
Excellent! Thanks
