### ISSUE TITLE
why upload pom.xml or .pom files after other files?

### ISSUE THREAD

**Issue by AkeemMYU** [JFrogDev/nexus2artifactory#62]
```python
class Maven(object):
    def __init__(self):
        self.lock = threading.Lock()
        self.poms = []

    def deployPaths(self, localpath, metapath, repo, repopath):
        fname = os.path.basename(repopath)
        if fname == 'pom.xml' or fname.endswith('.pom'):
            pom = localpath, metapath, repo, repopath
            with self.lock: self.poms.append(pom)
            return []
        return [(localpath, metapath, repo, repopath, {})]

    def cleanup(self):
        for localpath, metapath, repo, repopath in self.poms:
            yield localpath, metapath, repo, repopath, {}
```
Since items are only appended to self.poms and never deleted, when I run migration repeatedly, the same pom file will be uploaded multiple times.

**Comment by DarthFennec** [comment]
Whoops, oversight on my part, thanks for the PR. Another user had a problem with poms deploying before the artifacts they reference, I don't remember exactly what the problem was, but I expect Artifactory might have rejected poms that were uploaded too early or something. So that's why we're deploying poms last.
